2018-12-17T09:58:57|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 67, in connect
    self.gcs.CST(self.gcs.axes, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 3025, in CST
    axes, values = getitemsvaluestuple(axes, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 142, in getitemsvaluestuple
    checksize((True, True), items, values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 412, in checksize
    raise TypeError('a required parameter is missing')
TypeError: a required parameter is missing

